extends SceneTree
func _initialize() -> void:
	var canvas = load("res://addons/asset_pipeline/subject_box_canvas.gd").new()
	root.add_child(canvas)
	canvas.size = Vector2(400,400)
	var img := Image.create(200,100,false,Image.FORMAT_RGBA8)
	img.fill(Color.WHITE)
	canvas.set_image(img)
	assert(canvas.image_rect() == Rect2(0,100,400,200))
	assert(canvas.pixel_point(Vector2(200,200)) == Vector2(100,50))
	canvas.box = Rect2(10,10,50,50)
	canvas.color = Color.CYAN
	var marked: Image = canvas.annotated()
	assert(marked.get_pixel(10,10) == Color.CYAN)
	assert(marked.get_pixel(30,30) == Color.WHITE)
	assert(img.get_pixel(10,10) == Color.WHITE)
	var large := Image.create(3200, 2000, false, Image.FORMAT_RGBA8)
	large.fill(Color.WHITE)
	canvas.set_image(large)
	assert(canvas.texture.get_width() == 1600)
	assert(canvas.source.get_width() == 3200)
	canvas.box = Rect2(100, 100, 100, 100)
	assert(canvas.annotated().get_width() == 3200)
	var picker = load("res://addons/asset_pipeline/subject_picker.gd").new()
	root.add_child(picker)
	var host := Control.new()
	picker.setup(host)
	print("Subject canvas coordinate mapping, outline export, original preservation and window construction passed")
	picker.queue_free()
	host.free()
	canvas.queue_free()
	quit()
